export const defaultTodoList = [
  {
    id: 1,
    title: "Đi chợ mua đồ ăn cho cả tuần",
    isImportant: true,
    isCompleted: false,
    isDeleted: false,
    category: "personal",
  },
  {
    id: 2,
    title: "Viết báo cáo tiến độ dự án",
    isImportant: true,
    isCompleted: false,
    isDeleted: false,
    category: "company",
  },
  {
    id: 3,
    title: "Chạy bộ 5km buổi sáng",
    isImportant: false,
    isCompleted: true,
    isDeleted: false,
    category: "sport",
  },
  {
    id: 4,
    title: "Chuẩn bị slide thuyết trình nhóm",
    isImportant: true,
    isCompleted: false,
    isDeleted: false,
    category: "company",
  },
  {
    id: 5,
    title: "Đặt vé máy bay đi Đà Nẵng",
    isImportant: false,
    isCompleted: false,
    isDeleted: false,
    category: "travel",
  },
  {
    id: 6,
    title: "Hẹn gặp bạn uống cà phê",
    isImportant: false,
    isCompleted: false,
    isDeleted: false,
    category: "personal",
  },
  {
    id: 7,
    title: "Họp nhóm dự án lúc 9h sáng",
    isImportant: true,
    isCompleted: true,
    isDeleted: false,
    category: "company",
  },
  {
    id: 8,
    title: "Tham gia lớp yoga buổi tối",
    isImportant: false,
    isCompleted: false,
    isDeleted: false,
    category: "sport",
  },
  {
    id: 9,
    title: "Chuẩn bị vali du lịch",
    isImportant: true,
    isCompleted: false,
    isDeleted: false,
    category: "travel",
  },
  {
    id: 10,
    title: "Gọi điện hỏi thăm gia đình",
    isImportant: false,
    isCompleted: true,
    isDeleted: false,
    category: "personal",
  },
];
